from __future__ import annotations

from narrativefield.schema.agents import AgentState
from narrativefield.schema.world import WorldDefinition
from narrativefield.simulation.types import WorldState


WORLD_DEFINITION_DICT: dict = {
    "id": "dinner_party_01",
    "name": "The Dinner Party",
    "description": "Six guests gather for an evening dinner. Beneath the polished surface, a web of secrets, affairs, and financial betrayal threatens to unravel.",
    "sim_duration_minutes": 150.0,
    "ticks_per_minute": 2.0,
    "locations": {
        "dining_table": {
            "id": "dining_table",
            "name": "Dining Table",
            "privacy": 0.1,
            "capacity": 6,
            "adjacent": ["kitchen", "foyer", "balcony", "bathroom"],
            # Open-plan: the table can sometimes overhear kitchen drama.
            "overhear_from": ["kitchen"],
            "overhear_probability": 0.3,
            "description": "The main dining table. Seats six. The social center of the evening.",
        },
        "kitchen": {
            "id": "kitchen",
            "name": "Kitchen",
            "privacy": 0.5,
            "capacity": 3,
            "adjacent": ["dining_table"],
            "overhear_from": [],
            "overhear_probability": 0.0,
            "description": "An open-plan kitchen adjacent to the dining area.",
        },
        "balcony": {
            "id": "balcony",
            "name": "Balcony",
            "privacy": 0.7,
            "capacity": 3,
            "adjacent": ["dining_table"],
            "overhear_from": [],
            "overhear_probability": 0.0,
            "description": "A small balcony off the dining room. Private enough for real conversations.",
        },
        "foyer": {
            "id": "foyer",
            "name": "Foyer",
            "privacy": 0.55,
            "capacity": 4,
            "adjacent": ["dining_table", "bathroom"],
            "overhear_from": [],
            "overhear_probability": 0.0,
            "description": "The entrance hallway.",
        },
        "bathroom": {
            "id": "bathroom",
            "name": "Bathroom",
            "privacy": 0.9,
            "capacity": 1,
            "adjacent": ["foyer", "dining_table"],
            "overhear_from": [],
            "overhear_probability": 0.0,
            "description": "A small bathroom down the hall. The most private space available.",
        },
    },
    "secrets": {
        "secret_affair_01": {
            "id": "secret_affair_01",
            "description": "Elena and Marcus are having a romantic affair behind Thorne's back.",
            "truth_value": True,
            "holder": ["elena"],
            "about": "elena",
            "content_type": "affair",
            "initial_knowers": ["elena", "marcus", "diana"],
            "initial_suspecters": ["lydia"],
            "dramatic_weight": 1.0,
            "reveal_consequences": "Thorne's marriage and business partnership are both destroyed.",
        },
        "secret_embezzle_01": {
            "id": "secret_embezzle_01",
            "description": "Marcus has been embezzling money from the business he shares with Thorne.",
            "truth_value": True,
            "holder": ["marcus"],
            "about": "marcus",
            "content_type": "financial",
            "initial_knowers": ["marcus"],
            "initial_suspecters": ["lydia", "victor"],
            "dramatic_weight": 0.9,
            "reveal_consequences": "Marcus faces criminal charges. Thorne realizes double betrayal.",
        },
        "secret_diana_debt": {
            "id": "secret_diana_debt",
            "description": "Diana owes Marcus a large sum of money.",
            "truth_value": True,
            "holder": ["diana"],
            "about": "diana",
            "content_type": "financial",
            "initial_knowers": ["diana", "marcus"],
            "initial_suspecters": [],
            "dramatic_weight": 0.6,
            "reveal_consequences": "Diana's loyalty conflict becomes public.",
        },
        "secret_lydia_knows": {
            "id": "secret_lydia_knows",
            "description": "Lydia has noticed financial discrepancies and suspects Marcus.",
            "truth_value": True,
            "holder": ["lydia"],
            "about": "lydia",
            "content_type": "knowledge",
            "initial_knowers": ["lydia"],
            "initial_suspecters": [],
            "dramatic_weight": 0.5,
            "reveal_consequences": "If Marcus learns, Lydia becomes a threat.",
        },
        "secret_victor_investigation": {
            "id": "secret_victor_investigation",
            "description": "Victor is investigating Marcus for a journalistic expose.",
            "truth_value": True,
            "holder": ["victor"],
            "about": "victor",
            "content_type": "investigation",
            "initial_knowers": ["victor"],
            "initial_suspecters": ["marcus"],
            "dramatic_weight": 0.7,
            "reveal_consequences": "Marcus discovers the investigation and reacts.",
        },
    },
    "claims": {
        "claim_thorne_health": {
            "id": "claim_thorne_health",
            "description": "Thorne has been seeing a specialist — his health may be declining.",
            "truth_status": "unknown",
            "claim_type": "rumor",
            "scope": "private",
            "holder": ["elena"],
            "about": "thorne",
            "content_type": "personal",
            "source_event_ids": [],
            "initial_knowers": ["elena"],
            "initial_suspecters": [],
            "dramatic_weight": 0.4,
            "reveal_consequences": "Changes the power dynamics — concern or opportunity?",
            "propagation_rate": 0.6,
            "decay_rate": 0.1,
        },
        "claim_guild_pressure": {
            "id": "claim_guild_pressure",
            "description": "The investment board is asking questions about Thorne's fund performance.",
            "truth_status": "true",
            "claim_type": "rumor",
            "scope": "private",
            "holder": ["victor"],
            "about": "thorne",
            "content_type": "financial",
            "source_event_ids": [],
            "initial_knowers": ["victor", "marcus"],
            "initial_suspecters": ["lydia"],
            "dramatic_weight": 0.5,
            "reveal_consequences": "Thorne realizes the investigation is wider than he thought.",
            "propagation_rate": 0.4,
            "decay_rate": 0.2,
        },
    },
    "seating": {
        "thorne": ["elena", "victor"],
        "elena": ["thorne", "marcus"],
        "marcus": ["elena", "diana"],
        "diana": ["marcus", "lydia"],
        "lydia": ["diana", "victor"],
        "victor": ["lydia", "thorne"],
    },
    "primary_themes": ["loyalty_betrayal", "truth_deception"],
    "snapshot_interval": 20,
    "catastrophe_threshold": 0.32,
    "composure_gate": 0.38,
    "trust_repair_multiplier": 3.0,
}


AGENT_DICTS: list[dict] = [
    {
        "id": "thorne",
        "name": "James Thorne",
        "location": "dining_table",
        "goals": {
            "safety": 0.4,
            "status": 0.9,
            "closeness": {"elena": 0.7, "marcus": 0.6, "lydia": 0.3, "diana": 0.4, "victor": 0.5},
            "secrecy": 0.3,
            "truth_seeking": 0.6,
            "autonomy": 0.7,
            "loyalty": 0.8,
        },
        "flaws": [
            {
                "flaw_type": "pride",
                "strength": 0.8,
                "trigger": "status_threat",
                "effect": "overweight_status",
                "description": "Thorne's self-image as a successful, respected man is his armor. Anything that threatens this image triggers an outsized reaction.",
            }
        ],
        "pacing": {
            "dramatic_budget": 1.0,
            "stress": 0.45,
            "composure": 0.34,
            "commitment": 0.65,
            "recovery_timer": 0,
            "suppression_count": 1,
        },
        "emotional_state": {"anger": 0.0, "fear": 0.0, "hope": 0.3, "shame": 0.0, "affection": 0.4, "suspicion": 0.1},
        "relationships": {
            "elena": {"trust": 0.8, "affection": 0.6, "obligation": 0.3},
            "marcus": {"trust": 0.7, "affection": 0.4, "obligation": 0.2},
            "lydia": {"trust": 0.3, "affection": 0.2, "obligation": 0.0},
            "diana": {"trust": 0.5, "affection": 0.3, "obligation": 0.1},
            "victor": {"trust": 0.6, "affection": 0.3, "obligation": 0.1},
        },
        "beliefs": {
            "secret_affair_01": "unknown",
            "secret_embezzle_01": "unknown",
            "secret_diana_debt": "unknown",
            "secret_lydia_knows": "unknown",
            "secret_victor_investigation": "unknown",
        },
        "alcohol_level": 0.0,
        "commitments": [],
    },
    {
        "id": "elena",
        "name": "Elena Thorne",
        "location": "dining_table",
        "goals": {
            "safety": 0.7,
            "status": 0.4,
            "closeness": {"thorne": 0.1, "marcus": 0.8, "lydia": 0.2, "diana": 0.6, "victor": 0.2},
            "secrecy": 0.9,
            "truth_seeking": 0.4,
            "autonomy": 0.8,
            "loyalty": 0.3,
        },
        "flaws": [
            {
                "flaw_type": "guilt",
                "strength": 0.7,
                "trigger": "intimacy_offered",
                "effect": "self_sacrifice",
                "description": "Elena's guilt about the affair makes her overly accommodating to Thorne, which paradoxically increases her stress.",
            },
            {
                "flaw_type": "cowardice",
                "strength": 0.65,
                "trigger": "conflict_nearby",
                "effect": "avoid_confrontation",
                "description": "Elena will go to great lengths to avoid direct conflict, preferring to flee or deflect.",
            },
        ],
        "pacing": {
            "dramatic_budget": 1.0,
            "stress": 0.45,
            "composure": 0.34,
            "commitment": 0.65,
            "recovery_timer": 0,
            "suppression_count": 1,
        },
        "emotional_state": {"anger": 0.0, "fear": 0.2, "hope": 0.2, "shame": 0.3, "affection": 0.3, "suspicion": 0.0},
        "relationships": {
            "thorne": {"trust": 0.3, "affection": 0.1, "obligation": 0.6},
            "marcus": {"trust": 0.7, "affection": 0.8, "obligation": 0.2},
            "lydia": {"trust": 0.2, "affection": 0.1, "obligation": 0.0},
            "diana": {"trust": 0.7, "affection": 0.5, "obligation": 0.1},
            "victor": {"trust": 0.3, "affection": 0.1, "obligation": 0.0},
        },
        "beliefs": {
            "secret_affair_01": "believes_true",
            "secret_embezzle_01": "unknown",
            "secret_diana_debt": "suspects",
            "secret_lydia_knows": "unknown",
            "secret_victor_investigation": "unknown",
        },
        "alcohol_level": 0.0,
        "commitments": ["maintain_affair_secrecy"],
    },
    {
        "id": "marcus",
        "name": "Marcus Webb",
        "location": "dining_table",
        "goals": {
            "safety": 0.8,
            "status": 0.7,
            "closeness": {"thorne": 0.3, "elena": 0.6, "lydia": 0.1, "diana": 0.2, "victor": -0.3},
            "secrecy": 1.0,
            "truth_seeking": 0.1,
            "autonomy": 0.6,
            "loyalty": 0.2,
        },
        "flaws": [
            {
                "flaw_type": "ambition",
                "strength": 0.8,
                "trigger": "loss_imminent",
                "effect": "overcommit",
                "description": "Marcus doubles down when cornered. Rather than cutting losses, he escalates deceptions.",
            },
            {
                "flaw_type": "denial",
                "strength": 0.6,
                "trigger": "betrayal_detected",
                "effect": "deny_evidence",
                "description": "Marcus refuses to acknowledge the harm his actions cause. He rationalizes everything.",
            },
        ],
        "pacing": {
            "dramatic_budget": 1.0,
            "stress": 0.42,
            "composure": 0.75,
            "commitment": 0.65,
            "recovery_timer": 0,
            "suppression_count": 0,
        },
        "emotional_state": {"anger": 0.0, "fear": 0.35, "hope": 0.1, "shame": 0.1, "affection": 0.2, "suspicion": 0.2},
        "relationships": {
            "thorne": {"trust": 0.2, "affection": 0.1, "obligation": 0.5},
            "elena": {"trust": 0.5, "affection": 0.5, "obligation": 0.3},
            "lydia": {"trust": 0.1, "affection": 0.0, "obligation": 0.0},
            "diana": {"trust": 0.2, "affection": 0.1, "obligation": 0.0},
            "victor": {"trust": -0.3, "affection": -0.2, "obligation": 0.0},
        },
        "beliefs": {
            "secret_affair_01": "believes_true",
            "secret_embezzle_01": "believes_true",
            "secret_diana_debt": "unknown",
            "secret_lydia_knows": "unknown",
            "secret_victor_investigation": "suspects",
        },
        "alcohol_level": 0.0,
        "commitments": ["maintain_affair_secrecy", "cover_embezzlement"],
    },
    {
        "id": "lydia",
        "name": "Lydia Cross",
        "location": "dining_table",
        "goals": {
            "safety": 0.8,
            "status": 0.3,
            "closeness": {"thorne": 0.5, "elena": 0.1, "marcus": -0.2, "diana": 0.3, "victor": 0.4},
            "secrecy": 0.4,
            "truth_seeking": 0.8,
            "autonomy": 0.5,
            "loyalty": 0.9,
        },
        "flaws": [
            {
                "flaw_type": "cowardice",
                "strength": 0.7,
                "trigger": "conflict_nearby",
                "effect": "avoid_confrontation",
                "description": "Lydia knows things that could blow the evening apart, but her fear of conflict keeps her silent.",
            },
            {
                "flaw_type": "loyalty",
                "strength": 0.6,
                "trigger": "betrayal_detected",
                "effect": "self_sacrifice",
                "description": "Lydia's loyalty to Thorne means she'll endure personal risk to protect him, even when telling him the truth would cause a scene.",
            },
        ],
        "pacing": {
            "dramatic_budget": 1.0,
            "stress": 0.2,
            "composure": 0.8,
            "commitment": 0.3,
            "recovery_timer": 0,
            "suppression_count": 0,
        },
        "emotional_state": {"anger": 0.1, "fear": 0.2, "hope": 0.1, "shame": 0.0, "affection": 0.2, "suspicion": 0.5},
        "relationships": {
            "thorne": {"trust": 0.7, "affection": 0.4, "obligation": 0.6},
            "elena": {"trust": 0.2, "affection": 0.1, "obligation": 0.0},
            "marcus": {"trust": -0.2, "affection": -0.1, "obligation": 0.0},
            "diana": {"trust": 0.4, "affection": 0.3, "obligation": 0.0},
            "victor": {"trust": 0.5, "affection": 0.2, "obligation": 0.0},
        },
        "beliefs": {
            "secret_affair_01": "suspects",
            "secret_embezzle_01": "suspects",
            "secret_diana_debt": "unknown",
            "secret_lydia_knows": "believes_true",
            "secret_victor_investigation": "unknown",
        },
        "alcohol_level": 0.0,
        "commitments": [],
    },
    {
        "id": "diana",
        "name": "Diana Forrest",
        "location": "dining_table",
        "goals": {
            "safety": 0.6,
            "status": 0.5,
            "closeness": {"thorne": 0.3, "elena": 0.7, "marcus": -0.1, "lydia": 0.3, "victor": 0.2},
            "secrecy": 0.7,
            "truth_seeking": 0.4,
            "autonomy": 0.6,
            "loyalty": 0.7,
        },
        "flaws": [
            {
                "flaw_type": "guilt",
                "strength": 0.6,
                "trigger": "intimacy_offered",
                "effect": "self_sacrifice",
                "description": "Diana feels guilty about her debt to Marcus and about keeping Elena's secret from Thorne. This guilt makes her over-accommodate everyone.",
            },
            {
                "flaw_type": "jealousy",
                "strength": 0.4,
                "trigger": "rejection",
                "effect": "escalate_conflict",
                "description": "Diana envies Elena's comfortable life and Thorne's wealth, even as she sympathizes with Elena's unhappiness.",
            },
        ],
        "pacing": {
            "dramatic_budget": 1.0,
            "stress": 0.45,
            "composure": 0.34,
            "commitment": 0.65,
            "recovery_timer": 0,
            "suppression_count": 1,
        },
        "emotional_state": {"anger": 0.0, "fear": 0.1, "hope": 0.2, "shame": 0.2, "affection": 0.3, "suspicion": 0.1},
        "relationships": {
            "thorne": {"trust": 0.4, "affection": 0.3, "obligation": 0.1},
            "elena": {"trust": 0.7, "affection": 0.6, "obligation": 0.2},
            "marcus": {"trust": 0.1, "affection": -0.1, "obligation": 0.7},
            "lydia": {"trust": 0.3, "affection": 0.2, "obligation": 0.0},
            "victor": {"trust": 0.3, "affection": 0.2, "obligation": 0.0},
        },
        "beliefs": {
            "secret_affair_01": "believes_true",
            "secret_embezzle_01": "unknown",
            "secret_diana_debt": "believes_true",
            "secret_lydia_knows": "unknown",
            "secret_victor_investigation": "unknown",
        },
        "alcohol_level": 0.0,
        "commitments": ["keep_elena_secret"],
    },
    {
        "id": "victor",
        "name": "Victor Hale",
        "location": "dining_table",
        "goals": {
            "safety": 0.4,
            "status": 0.6,
            "closeness": {"thorne": 0.5, "elena": 0.1, "marcus": -0.2, "lydia": 0.3, "diana": 0.1},
            "secrecy": 0.6,
            "truth_seeking": 0.68,
            "autonomy": 0.8,
            "loyalty": 0.4,
        },
        "flaws": [
            {
                "flaw_type": "obsession",
                "strength": 0.45,
                "trigger": "secret_exposure",
                "effect": "fixate_on_target",
                "description": "Victor's journalist instinct takes over when he smells a story. He'll push too hard, burn relationships, and ignore social cues in pursuit of the truth.",
            },
            {
                "flaw_type": "vanity",
                "strength": 0.4,
                "trigger": "authority_challenge",
                "effect": "seek_validation",
                "description": "Victor values being seen as the smartest person in the room. He'll drop hints about what he knows to show off, even when discretion would serve him better.",
            },
        ],
        "pacing": {
            "dramatic_budget": 1.0,
            "stress": 0.08,
            "composure": 0.97,
            "commitment": 0.10,
            "recovery_timer": 0,
            "suppression_count": 0,
        },
        "emotional_state": {"anger": 0.0, "fear": 0.0, "hope": 0.3, "shame": 0.0, "affection": 0.1, "suspicion": 0.3},
        "relationships": {
            "thorne": {"trust": 0.5, "affection": 0.4, "obligation": 0.1},
            "elena": {"trust": 0.3, "affection": 0.1, "obligation": 0.0},
            "marcus": {"trust": -0.1, "affection": 0.0, "obligation": 0.0},
            "lydia": {"trust": 0.3, "affection": 0.1, "obligation": 0.0},
            "diana": {"trust": 0.2, "affection": 0.1, "obligation": 0.0},
        },
        "beliefs": {
            "secret_affair_01": "unknown",
            "secret_embezzle_01": "suspects",
            "secret_diana_debt": "unknown",
            "secret_lydia_knows": "unknown",
            "secret_victor_investigation": "believes_true",
        },
        "alcohol_level": 0.0,
        "commitments": ["write_expose_on_marcus"],
    },
]


def create_dinner_party_world() -> WorldState:
    """Create the canonical dinner party initial world state (agents.md + world.md)."""

    definition = WorldDefinition.from_dict(WORLD_DEFINITION_DICT)
    agents = {a["id"]: AgentState.from_dict(a) for a in AGENT_DICTS}
    return WorldState(definition=definition, agents=agents, sim_time=0.0, tick_id=0, event_log=[], event_seq=0)
